# Typos configuration for spell checking
# https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
  # Ignore hex colors
  "#[0-9a-fA-F]{6}",
  # Ignore URLs
  "https?://[^\\s]+",
]

[default.extend-words]
# Add project-specific words that are not typos
# Format: word = "word" or incorrectword = "correctword"

[files]
extend-exclude = [
  "node_modules",
  ".next",
  ".turbo",
  "pnpm-lock.yaml",
  "package-lock.json",
  "*.svg",
  "*.png",
  "*.jpg",
  "*.jpeg",
  "*.gif",
  "*.ico",
  "*.woff",
  "*.woff2",
  "*.ttf",
  "*.eot",
  "output.css",
]
