name: Dotenv Linter

on:
  pull_request:
    branches: [main, develop]
    paths:
      - '.env.example'
      - '.env.*'

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dotenv-linter:
    name: Lint Environment Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run dotenv-linter
        uses: dotenv-linter/action-dotenv-linter@v2
        with:
          reporter: github-code-suggestions
        continue-on-error: false
